### ISSUE TITLE
Fjern joark soap klienter

### ISSUE THREAD

**Issue by frode-carlsen** [navikt/fp-felles#335]
- inngaaendejournal-klient                           
: brukes av k9-fordel, fp-fordel, k9-klage, fptilbake (byttes til SAF)
- behandleinngaendejournal-klient               
: brukes av k9-fordel, fp-fordel
- kodeverk-klient                                           
 : Er lite/ikke behov for integrasjon annet enn kanskje postnummer/sted. Flytt evt. gjenstående til fpsak
- journal-klient                                                 
: brukes av fp-sak, k9-klage, fptilbake, spberegning, fpfordel   (byttes til SAF)
- mottainngaaendeforsendelse-klient          
: brukes kun av https://github.com/navikt/fpfordel
- arbeidsforhold-klient                                  
 : brukes av fp-risk, fp-abakus, spberegning.

**Comment by jolarsen** [comment]
journal-klient dvs JournalV3 må beholdes inntil FP er over på nytt saksregime.
Det er litt mer intrikat enn først tenkt pga dokprod som krever arkivsak. En ukes mer synk-jobb
SAF kan ikke overta for JournalV3 før hele transisjonen er gjort.
