### ISSUE TITLE
ProsesstaskInputDto valideres ikke i fpsak

### ISSUE THREAD

**Issue by junnae** [navikt/fp-felles#51]
Testen alle_felter_i_objekter_som_brukes_som_inputDTO_skal_enten_ha_valideringsannotering_eller_være_av_godkjent_type  godkjenner ikke 
no.nav.vedtak.felles.prosesstask.rest.dto.ProsessTaskOpprettInputDto
Jeg prøvde å legge til size og Valid annotering, men nå feiler den på

java.lang.ClassCastException: java.base/sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeBaseImpl cannot be cast to java.base/java.lang.reflect.AnnotatedParameterizedType

**Comment by ekun** [comment]
Det er ikke feil med noe i felles, det er testen som må håndtere det å møte på properties.
