### ISSUE TITLE
Fjern UnleashKlient

### ISSUE THREAD

**Issue by mrsladek** [navikt/fp-felles#766]
Det brukes kun i fp-sak i apiet til frontend. Noe usikker om fp-frontend bruker dette grensesnittet. 
Kan mulig fjernes.

**Comment by jan-olaveide** [comment]
Først deprecate, deretter fjerne om N+2. er vi der nå?

**Comment by mrsladek** [comment]
Jeg har bare annotert den med @Deprecated(since 3.2)
